version: 2
updates:
    - package-ecosystem: "cargo"
      directory: "/"
      schedule:
          interval: "daily"
          time: "00:00"
          timezone: "Etc/UTC"
      cooldown:
          default-days: 1
          include:
              - "*"
      commit-message:
          prefix: "chore"
      ignore:
          - dependency-name: "async-std"
            update-types:
                - "version-update:semver-minor"
                - "version-update:semver-patch"
          - dependency-name: "smol"
            update-types:
                - "version-update:semver-minor"
                - "version-update:semver-patch"
          - dependency-name: "tokio"
            update-types:
                - "version-update:semver-minor"
                - "version-update:semver-patch"
